# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 23:55
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Column', verbose_name='belong to'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='notDraft'),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=256, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.CharField(default='', max_length=256, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='column',
            name='intro',
            field=models.TextField(default='', verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=256, verbose_name='column_name'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='profile',
            field=models.CharField(default='', max_length=256, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
