# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(verbose_name='线上路径')),
                ('dt', models.DateTimeField(verbose_name='时间')),
                ('data_rid', models.CharField(max_length=20, verbose_name='房间ID')),
                ('upload_to', models.URLField(verbose_name='本地路径')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rid', models.CharField(max_length=20, verbose_name='房间ID')),
                ('data_rpos', models.CharField(max_length=20, verbose_name='')),
                ('data_sid', models.CharField(max_length=20, verbose_name='')),
                ('data_sub_rt', models.CharField(max_length=20, verbose_name='')),
                ('data_tid', models.CharField(max_length=20, verbose_name='')),
                ('dt', models.DateTimeField(verbose_name='时间')),
                ('dy_name', models.CharField(max_length=50, verbose_name='账号名字')),
                ('dy_num', models.CharField(max_length=20, verbose_name='观看数')),
                ('gif', models.CharField(max_length=120, verbose_name='GIF')),
                ('href', models.CharField(max_length=20, verbose_name='房间url')),
                ('img', models.CharField(max_length=120, verbose_name='IMG_url')),
                ('tag', models.CharField(max_length=120, verbose_name='标签')),
                ('target', models.CharField(max_length=20, verbose_name='目标')),
                ('title0', models.CharField(max_length=120, verbose_name='标题')),
            ],
            options={
                'verbose_name': '斗鱼时间信息',
                'verbose_name_plural': '斗鱼时间信息180条',
            },
        ),
    ]
