# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='data_rpos',
            field=models.CharField(max_length=20, verbose_name='data_rpos'),
        ),
        migrations.AlterField(
            model_name='info',
            name='data_sid',
            field=models.CharField(max_length=20, verbose_name='data_sid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='data_sub_rt',
            field=models.CharField(max_length=20, verbose_name='data_sub_rt'),
        ),
    ]
