# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 07:41
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='None', max_length=30)),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('dt', models.DateTimeField(verbose_name='DatetimeCommit')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LastPostID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdt', models.DateTimeField(verbose_name='DatetimeCommit')),
                ('postid', models.IntegerField()),
            ],
        ),
    ]
