# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题两三字')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('pic', models.ImageField(default='uploads/default.jpg', upload_to='uploads/', verbose_name='小图片110x80')),
                ('url', models.CharField(max_length=100, verbose_name='超链接')),
            ],
            options={
                'verbose_name': '4张轮播广告图',
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='不采用', max_length=100, verbose_name='图片名称')),
                ('pic', models.ImageField(default='uploads/default.jpg', upload_to='uploads/', verbose_name='小图片110x80')),
                ('published', models.BooleanField(default=True, verbose_name='选用')),
            ],
            options={
                'verbose_name': '4张小图片110x80',
            },
        ),
        migrations.CreateModel(
            name='Says',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, verbose_name='发布')),
                ('title', models.CharField(max_length=100, verbose_name='标题两三字')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('cate', models.CharField(max_length=30, verbose_name='末尾按钮')),
                ('url', models.CharField(max_length=100, verbose_name='超链接')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 9, 9, 11, 722610, tzinfo=utc), verbose_name='留言日期')),
            ],
            options={
                'verbose_name': '留言',
            },
        ),
    ]
