# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 02:29
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='图片标题')),
                ('homepic', models.ImageField(default='uploads/jnu/images/default.jpg', upload_to='uploads/jnu/images/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页中部栏左侧图片',
            },
        ),
        migrations.CreateModel(
            name='WeiXinArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_top', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='uploads/jnu/images/default.jpg', upload_to='uploads/jnu/images/', verbose_name='文章标头图片535*270')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='暨大信息科学院', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='暨大信息科学院', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='news', max_length=255, verbose_name='默认网址勿改')),
                ('Tag', models.CharField(max_length=155, verbose_name='标签')),
            ],
            options={
                'verbose_name': '微信文章',
            },
        ),
    ]
