# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 01:26
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_top', models.BooleanField(default=False, verbose_name='设为置顶')),
                ('pic', models.ImageField(default='uploads/blog/images/default.jpg', upload_to='uploads/blog/images/', verbose_name='文章标头图片535*270')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='章半仙', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='本网', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='./#', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='homeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='图片标题')),
                ('homepic', models.ImageField(default='uploads/blog/images/default.jpg', upload_to='uploads/blog/images/', verbose_name='首页中部栏左侧图片553*300')),
            ],
            options={
                'verbose_name': '首页中部栏左侧图片',
            },
        ),
    ]
