# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='章半仙', max_length=255, verbose_name='名字')),
                ('source_from', models.CharField(default='本网', max_length=255, verbose_name='来源')),
                ('describtion', models.CharField(default=' ', max_length=255, verbose_name='描述')),
                ('features', models.CharField(default=' ', max_length=255, verbose_name='特征')),
                ('cookies', models.CharField(default=' ', max_length=255, verbose_name='记录')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='homeImage',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
