# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='says',
            name='pub_date',
            field=models.DateTimeField(verbose_name='留言日期'),
        ),
    ]
